version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app_blue
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - laravel

networks:
  laravel:
    external: true
