name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            cd /home/ec2-user/apps/laravel-app

            git pull origin main

            echo "Writing .env"
            cat <<EOF > .env
APP_ENV=production
APP_DEBUG=false
APP_KEY=${{ secrets.PROD_APP_KEY }}
APP_URL=${{ secrets.PROD_APP_URL }}

DB_CONNECTION=mysql
DB_HOST=${{ secrets.PROD_DB_HOST }}
DB_PORT=3306
DB_DATABASE=${{ secrets.PROD_DB_NAME }}
DB_USERNAME=${{ secrets.PROD_DB_USER }}
DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}
EOF

            docker compose down
            docker compose up -d --build

            docker exec laravel_app php artisan migrate --force
            docker exec laravel_app php artisan optimize
